"""Add unique constraint to sleep_schedule

Revision ID: 1f958721566c
Revises: 2de881feb5e2
Create Date: 2023-09-05 16:27:07.523602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f958721566c'
down_revision: Union[str, None] = '2de881feb5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_schedule', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_babies_schedule', ['babies_id', 'schedule_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_schedule', schema=None) as batch_op:
        batch_op.drop_constraint('uq_babies_schedule', type_='unique')

    # ### end Alembic commands ###
