"""Add schedule_id to BabySleepSchedule

Revision ID: 2de881feb5e2
Revises: 9af13e2f49e7
Create Date: 2023-09-02 16:48:41.000383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de881feb5e2'
down_revision: Union[str, None] = '9af13e2f49e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_schedule', schema=None) as batch_op:
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###
