"""Create Baby Sleep Models

Revision ID: 6c8719e749e0
Revises: 
Create Date: 2023-09-02 06:30:25.140879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8719e749e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('babies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parents_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['parents_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('babies_id', sa.Integer(), nullable=True),
    sa.Column('sleep_start', sa.DateTime(), nullable=True),
    sa.Column('sleep_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['babies_id'], ['babies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_schedule')
    op.drop_table('babies')
    op.drop_table('parents')
    # ### end Alembic commands ###
