"""Add schedule relationship to Baby table

Revision ID: 9af13e2f49e7
Revises: 6c8719e749e0
Create Date: 2023-09-02 11:01:37.690156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af13e2f49e7'
down_revision: Union[str, None] = '6c8719e749e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
